<a href="https://colab.research.google.com/github/YuriiKlim/AI/blob/lesson2/Copy_of_%D0%94%D0%97_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль numpy

In [2]:
import numpy as np

#Завдання 1

Створіть масив з парними числами між 30 і 70

In [ ]:
array = np.arange(30, 71)

print(array)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


#Завдання 2
Створіть масив з 10 числами між 0(включно) та 1(не включно) див документацію

In [ ]:
lin = np.linspace(0, 0.99, num=10)

print(lin)

[0.   0.11 0.22 0.33 0.44 0.55 0.66 0.77 0.88 0.99]


#Завдання 4
Напишіть функцію яка приймає матрицю розміру nxn та повертає матрицю розміру (n+2) x (n+2), на краях якої розміщенні 0.

In [ ]:
def pad_with_zeros(matrix):
    n = matrix.shape[0]
    padded_matrix = np.zeros((n + 2, n + 2))
    padded_matrix[1:n+1, 1:n+1] = matrix
    return padded_matrix

example_matrix = np.array([[1, 2], [3, 4]])
padded_matrix = pad_with_zeros(example_matrix)

print(example_matrix)
print(padded_matrix)

array([[0., 0., 0., 0.],
       [0., 1., 2., 0.],
       [0., 3., 4., 0.],
       [0., 0., 0., 0.]])

#Завдання 5
У попередьньому масиві змініть тип даних. Виведіть тип даних до та після зміни

In [ ]:
original_dtype = padded_matrix.dtype
padded_matrix = padded_matrix.astype(np.float32)
new_dtype = padded_matrix.dtype

print(original_dtype, new_dtype)

(dtype('float32'), dtype('float32'))

#Завдання 6
У даному масиві замініть елементи, які дорівнюють\більші\менші за var на -1

In [ ]:
x = np.array([1, 5, 3, 8, 6, 5, 7, 4])
var = 5
equal = np.copy(x)
more = np.copy(x)
less = np.copy(x)

equal[equal == var] = -1
more[more > var] = -1
less[less < var] = -1

print(equal)
print(more)
print(less)

[ 1 -1  3  8  6 -1  7  4]
[ 1  5  3 -1 -1  5 -1  4]
[-1  5 -1  8  6  5  7 -1]


#Завдання 7
Замініть пропущені значення матриці(np.nan) на -1

Дивись np.isnan

In [ ]:
X = np.array([[1, 2, np.nan, 4],
              [5, np.nan, np.nan, 4],
              [np.nan, 10, 11, np.nan]])

X[np.isnan(X)] = -1

print(X)

[[ 1.  2. -1.  4.]
 [ 5. -1. -1.  4.]
 [-1. 10. 11. -1.]]


#Завдання 8
Створіть матрицю розміру 4х6 з випадковими числами. Змініть її розмір на 3х8

In [ ]:
random_matrix = np.random.random((4, 6))
reshaped_matrix = random_matrix.reshape(3, 8)

print(random_matrix, "\n")

print(reshaped_matrix)

[[0.61058846 0.11690407 0.13513504 0.88674734 0.35801029 0.40922414]
 [0.88448484 0.89526763 0.53330587 0.28531411 0.12750739 0.29712762]
 [0.48240913 0.66295793 0.59892658 0.05275073 0.24561491 0.67713262]
 [0.79104355 0.32399909 0.40973987 0.95988415 0.6998496  0.54185851]] 

[[0.61058846 0.11690407 0.13513504 0.88674734 0.35801029 0.40922414
  0.88448484 0.89526763]
 [0.53330587 0.28531411 0.12750739 0.29712762 0.48240913 0.66295793
  0.59892658 0.05275073]
 [0.24561491 0.67713262 0.79104355 0.32399909 0.40973987 0.95988415
  0.6998496  0.54185851]]


#Завдання 9
Створіть матрицю з одиниць розміром 3х4. Знайдіть середнє арифметичне(mean) кожного стовпчика

In [ ]:
ones_matrix = np.random.random((3, 4))

column_means = ones_matrix.mean(axis=0)

print(ones_matrix, "\n")
print(column_means)

[[0.98942214 0.96666569 0.27238101 0.45588513]
 [0.05012695 0.45349301 0.47873557 0.00111174]
 [0.03764764 0.73601762 0.72591401 0.06796055]] 

[0.35906558 0.71872544 0.49234353 0.17498581]


#Завдання 10
Створіть випадкову матрицю розміром 5х6. Округліть значення до одного знаку після коми(np.round). Розмістіть стовпчики так, щоб значення в першому рядку були відсортовані за зростанням

In [ ]:
random_matrix = np.random.rand(5, 6)

rounded_matrix = np.round(random_matrix, 1)

sorted_indices = np.argsort(rounded_matrix[0])
sorted_matrix = rounded_matrix[:, sorted_indices]

print(sorted_matrix)

[[0.1 0.2 0.3 0.6 0.7 0.8]
 [0.4 0.1 0.6 0.7 0.  0.6]
 [0.7 0.8 0.7 0.7 0.2 0.9]
 [0.6 0.6 0.9 0.1 0.6 0.5]
 [0.1 0.3 0.7 0.1 0.9 0.6]]


#Завдання 11
В даній матриці знайдіть всі елементи зі значенням між 3 і 6

Дивись документацію np.logical_and

In [6]:
X = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [9, 8, 7, 6, 5],
              [4, 3, 2, 1, 0]])

elements = X[(X >= 3) & (X <= 6)]

print(elements)

[3 4 5 6 6 5 4 3]


#Завдання 12
Створіть випадкову матрицю розміру 5х6. Нормалізуйте стовпчики: від кожного елемента ставпчика відніміть мінімальне значення та поділіть результат на різницю між максимальним та мінімальним елементом цього стовпчика.

Після цього всі значення мають бути в межах [0, 1]

In [7]:
random_matrix = np.random.rand(5, 6)

min_values = random_matrix.min(axis=0)
max_values = random_matrix.max(axis=0)
normalized_matrix = (random_matrix - min_values) / (max_values - min_values)

print(normalized_matrix)

[[0.81153705 0.64989418 0.         0.15303004 0.91742755 0.70558186]
 [0.8716317  0.         0.44361938 0.29332294 0.01473696 0.88600304]
 [1.         0.89802963 0.03982181 1.         0.         1.        ]
 [0.         1.         0.59475627 0.         1.         0.01743908]
 [0.49919721 0.47561866 1.         0.24271756 0.30371558 0.        ]]
