<a href="https://colab.research.google.com/github/YuriiKlim/AI/blob/lesson2/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль numpy

In [3]:
import numpy as np

# Завдання 1
Створіть масив з елементами від 1 до 12. Виведіть розмір та тип масиву

In [44]:
array = np.arange(1, 13)
print(array.shape)
print(type(array))
print(array.dtype)

(12,)
<class 'numpy.ndarray'>
int32


# Завдання 2
Зробіть на основі попереднього масиву матрицю з 4 стовчиками. Змініть тип даних матриці на float32. Виведіть транспоновану матрицю.

In [ ]:
matrix = array.reshape(-1, 4)
matrix = matrix.astype(np.float32)
transposed_matrix = matrix.T
print(transposed_matrix)

[[ 1.  5.  9.]
 [ 2.  6. 10.]
 [ 3.  7. 11.]
 [ 4.  8. 12.]]


#Завдання 3
Створіть матрицю 8х8 з 0 та 1 розміщеними в шаховому порядку

In [5]:
chessboard_matrix = np.zeros((8, 8), dtype=int)
chessboard_matrix[1::2, ::2] = 1
chessboard_matrix[::2, 1::2] = 1
print(chessboard_matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Завдання 4
Створіть випадкову матрицю 4х3. Знайдіть суму елементів в стовпчиках\рядках\усій матриці

In [36]:
random_matrix = np.random.rand(4, 3)

In [41]:
sum_columns = random_matrix.sum(axis=0)
sum_rows = random_matrix.sum(axis=1)
sum_total = random_matrix.sum()
print(sum_columns, sum_rows, sum_total)

[2.04733214 0.59221182 2.61155693] [1.35983992 0.72222049 2.02859656 1.14044393] 5.251100896654002


# Завдання 5
У попередній матриці від кожного рядка відніміть максимальний елемент цього рядка

In [42]:
adjusted_matrix = random_matrix - random_matrix.max(axis=1).reshape(-1, 1)
print(adjusted_matrix)

[[-0.62895365 -0.93834445  0.        ]
 [ 0.         -0.38646336 -0.23383443]
 [ 0.         -0.44358371 -0.08227382]
 [-0.25137939 -0.56706184  0.        ]]


# Завдання 6
Є дані про вагу контейнерів для перевезення на кораблі: дрібний - 5 т,  малий - 10 т, середній - 25 т, великий - 40 т. На кораблі розміщено 20 дрібних, 5 малих, 10 середніх та 4 великих контейнерів. Знайти масу вантажу.

In [46]:
weights_vector = np.array([5, 10, 25, 40])
counts_vector = np.array([20, 5, 10, 4])
total_weight_matrix_multiplication = np.dot(weights_vector, counts_vector)
print(total_weight_matrix_multiplication)

560


# Завдання 7
Тепер у нас декілька кораблів. Напишіть код для обчислення вантажу на кожному кораблі.

In [47]:
counts_matrix = np.array([
    [20, 5, 10, 4],
    [10, 8, 5, 6],
    [15, 2, 8, 3]
])

weights_vector = np.array([5, 10, 25, 40])

total_weights = np.dot(counts_matrix, weights_vector)
print(total_weights)

[560 495 415]
