<a href="https://colab.research.google.com/github/YuriiKlim/AI/blob/main/module2/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


**Матеріали**:

-   Корисні матеріали по numpy із зображеннями [A Visual Intro to NumPy](http://jalammar.github.io/visual-numpy/).


## Numpy

Numpy це модуль мови Python для швидких математичних обчислень. Він дозволяє створювати та обробляти масиви даних високих розмірностей.

Щоб використовувати `numpy`, нам спочатку потрібно імпортувати пакет numpy. За домовленістю ми імпортуємо його за допомогою псевдоніма `np`. Тоді, коли ми хочемо використовувати модулі або функції в цій бібліотеці, ми перед ними ставимо `np`.

In [3]:
import numpy as np

### Масиви

Масив numpy — це сітка однотипних значень. Кожен елемент індексується декількома числами, в залежності від розмірності масиву.

Створення на основі списків

In [ ]:
a = np.array([1, 2, 3])  # одновимірний масив



![](http://jalammar.github.io/images/numpy/create-numpy-array-1.png)

In [ ]:
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


Можна створювати масиви багатьох розмірностей

![](http://jalammar.github.io/images/numpy/numpy-array-create-2d.png)

![](http://jalammar.github.io/images/numpy/numpy-3d-array.png)

In [ ]:
b = np.array([[1,2],[3,4]])   # двовимірний масив
print(b)

[[1 2]
 [3 4]]


In [ ]:
print(b.shape)

(2, 2)


Часто бувають випадки, коли ми хочемо, щоб numpy ініціалізував для нас значення масиву. numpy надає такі методи, як `ones()`, `zeros()` і `random.random()` для цих випадків. Ми просто передаємо їм ту кількість елементів, яку ми хочемо створити

![](http://jalammar.github.io/images/numpy/create-numpy-array-ones-zeros-random.png)

Ми також можемо використовувати ці методи для створення багатовимірних масивів, якщо ми передаємо їм кортеж, що описує розміри матриці, яку ми хочемо створити:

![](http://jalammar.github.io/images/numpy/numpy-matrix-ones-zeros-random.png)

![](http://jalammar.github.io/images/numpy/numpy-3d-array-creation.png)

In [ ]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

[[0. 0.]
 [0. 0.]]


In [ ]:
b = np.ones((1,2))   # Create an array of all ones
print(b)

[[1. 1.]]


In [ ]:
c = np.full((2,2), 7) # Create a constant array
print(c)

[[7 7]
 [7 7]]


In [ ]:
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)

[[1. 0.]
 [0. 1.]]


In [ ]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

[[0.339443   0.69049703]
 [0.43957987 0.10161486]]


Нарешті, я хочу згадати дві дуже корисні функції для створення послідовностей чисел у визначеному діапазоні, а саме `arange` і `linspace`. Функція arange у NumPy має той самий синтаксис, що й об’єкти `range` в Python: якщо надано два аргументи, перший аргумент представляє початкове значення, а друге значення визначає кінцеве значення напіввідкритого інтервалу:

Numpy також має дві корисні функції для створення послідовностей чисел: `arange` і `linspace`.

Функція `arange` приймає три аргументи, які визначають початкове значення, кінцеве значення(яке на включається) інтервалу та розмір кроку. (Розмір кроку за замовчуванням, якщо не вказано явно, дорівнює 1; початкове значення за замовчуванням, якщо не вказано явно, дорівнює 0.)

Функція `linspace` схожа, але ми можемо вказати кількість значень замість розміру кроку, і вона створить послідовність рівномірно розташованих значень.

In [ ]:
f = np.arange(10,50,5)   # Create an array of values starting at 10 in increments of 5
print(f)

[10 15 20 25 30 35 40 45]


In [ ]:
g = np.linspace(0., 1., num=5)
print(g)

[0.   0.25 0.5  0.75 1.  ]


Іноді ми можемо захотіти побудувати масив із існуючих масивів, «складаючи» існуючі масиви вертикально або горизонтально. Ми можемо використовувати `vstack()` (або `row_stack`) і `hstack()` (або `column_stack`), відповідно.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(f"{a=}\n")
print(f"{b=}\n")
np.vstack((a,b))

a=array([1, 2, 3])

b=array([4, 5, 6])



array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a = np.array([[7], [8], [9]])
b = np.array([[4], [5], [6]])

print(f"{a=}\n")
print(f"{b=}\n")
np.hstack((a,b))

a=array([[7],
       [8],
       [9]])

b=array([[4],
       [5],
       [6]])



array([[7, 4],
       [8, 5],
       [9, 6]])

### Індекси


Numpy пропонує кілька способів індексування в масиви.

Ми можемо індексувати та використовувати розділення `slice` для масивів numpy усіма способами, як зі списками Python:

![](http://jalammar.github.io/images/numpy/numpy-array-slice.png)

І ви можете індексувати та розділяти масиви numpy у кількох вимірах. Якщо розрізати масив із кількома вимірами, ви повинні вказати зріз для кожного виміру:

![](http://jalammar.github.io/images/numpy/numpy-matrix-indexing.png)

In [ ]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

Фрагмент масиву — це перегляд тих самих даних, тому його зміна призведе до зміни оригінального масиву.

In [ ]:
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])

Ви також можете поєднувати цілі індекси з індексуванням фрагментів. Однак це призведе до масиву нижчого виміру, ніж вихідний масив.

In [ ]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Два способи доступу до даних у другому рядку масиву. Змішування цілочисельної індексації з фрагментами дає масив нижчого рангу, тоді як використання лише фрагментів дає масив того самого рангу, що й вихідний масив:

In [ ]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a

print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [ ]:
# Для стовпчиків
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


Індексування цілочисельного масиву: коли ви індексуєте масиви numpy за допомогою слайсів, отриманий масив завжди буде підмасивом вихідного масиву. Навпаки, індексація цілочисельного масиву дозволяє створювати довільні масиви, використовуючи дані з іншого масиву.

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)
print()

# An example of integer array indexing.
# Результатом є масив розміру (3,)
print(a[[0, 1, 2], [0, 1, 0]])
print()

# Даний рялок коду аналогічний наступному
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[[1 2]
 [3 4]
 [5 6]]

[1 4 5]
[1 4 5]


Отримані таким чином елементи можна змінювати у вихідному масиві

In [ ]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[range(4), b])  # Prints "[ 1  6  7 11]"

[ 1  6  7 11]


In [ ]:
# Mutate one element from each row of a using the indices in b
a[range(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


Логічне індексування масиву: логічне індексування масиву дозволяє вибирати довільні елементи масиву. Часто цей тип індексування використовується для вибору елементів масиву, які задовольняють певну умову.

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # знайти елементи які більше 2;
                    # поверне масив з True/False такого ж розміру як а
                    # де кожен елемент bool_idx каже
                    # чи виконується умова для відповідного елемента в а

print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [ ]:
# Використання логічного індексування поверне одновимірний масив
# з елементами які відповідають True

print(a[bool_idx])

# В одному рядку коду
print(a[a > 2])

Під час роботи з масивами numpy часто корисно отримати *індекси* (а не лише значення) елементів масиву, які відповідають певним умовам. Є кілька функцій numpy, які ви точно захочете запам’ятати:

-   [`argmax`](https://numpy.org/doc/stable/reference/generated/numpy.argmax.html) (індекс максимального елементу)
-   [`argmin`](https://numpy.org/doc/stable/reference/generated/numpy.argmin.html) (індекс мінімального елементу)
-   [`argsort`](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html) (відсортований список індексів за значенням елемента в порядку зростання)
-   [`where`](https://numpy.org/doc/stable/reference/generated/numpy.where.html) (індекси елементів, які відповідають певній умові)

In [ ]:
a = np.array([1, 8, 9, -3, 2, 4, 7, 9])

print(np.argmax(a))

print(np.argmin(a))

print(np.argsort(a))

print(np.argsort(a)[::-1])

print(np.where(a > 5)[0])

2
3
[3 0 4 5 6 1 2 7]
[7 2 1 6 5 4 0 3]
[1 2 6 7]


Більше інформації у документації

### Типи даних

Кожен масив numpy є сіткою елементів одного типу. Numpy надає великий набір числових типів даних, які можна використовувати для створення масивів. Numpy намагається вгадати тип даних, коли ви створюєте масив, але функції, які створюють масиви, зазвичай також включають необов’язковий аргумент для явного визначення типу даних.

In [ ]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


Більше тут [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

### Дії з масивами

Що робить роботу з `numpy` такою потужною та зручною, так це те, що він містить багато *векторизованих* математичних функцій для обчислень над елементами масиву. Ці функції дуже оптимізовані та *дуже* швидкі - набагато, набагато швидше, ніж використання явного циклу for.

Наприклад, давайте створимо великий масив випадкових значень, а потім підсумуємо його в обох напрямках. Ми використаємо `%%time` *cell magic*, щоб визначити час.

In [29]:
a = np.random.random(10000000)

In [32]:
%%time
x = np.sum(a)
print(x)

4998940.798476305
CPU times: total: 0 ns
Wall time: 12.3 ms


In [11]:
%%time
x = 0
for element in a:
  x = x + element

CPU times: total: 1.23 s
Wall time: 1.3 s


In [12]:
%%time
sum(a)

CPU times: total: 734 ms
Wall time: 752 ms


4999971.200859852

Зверніть увагу, наскільки швидша векторизована версія операції! Цей тип швидких обчислень є основним засобом машинного навчання, яке вимагає *багато* обчислень.

За можливості ми намагатимемося використовувати ці векторизовані операції.

Деякі математичні функції доступні як перевантаження операторів, так і функції в модулі numpy.


Наприклад, ви можете виконати поелементне підсумовування двох масивів за допомогою оператора + або функції `add()`.

![](http://jalammar.github.io/images/numpy/numpy-arrays-adding-1.png)

![](http://jalammar.github.io/images/numpy/numpy-matrix-arithmetic.png)

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


І це також працює для інших операцій, а не лише для додавання:

![](http://jalammar.github.io/images/numpy/numpy-array-subtract-multiply-divide.png)

In [ ]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

In [ ]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

In [ ]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

Можна використовуємо функцію `dot()` для обчислення скалярних добутків векторів, множення вектора на матрицю та множення матриць. `dot()` доступний і як функція в модулі numpy, і як метод екземпляра об’єктів масиву:

Корисне посилання: [Matrix maltuplication](http://www.mathsisfun.com/algebra/matrix-multiplying.html)

![](http://jalammar.github.io/images/numpy/numpy-matrix-dot-product-1.png)

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

219
219


Ви також можете використовувати оператор `@`, який еквівалентний функції `dot` numpy.

In [ ]:
print(v @ w)

219


In [ ]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

In [ ]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x, "\n")
print(y, "\n")
print(x @ y, "\n")

[[1 2]
 [3 4]] 

[[5 6]
 [7 8]] 

[[19 22]
 [43 50]] 



### Практика
Є масив калорійності продуктів та кількості продуктів у стравах. Знайти калорійності страв.

In [ ]:
# 1 страва, 1 метод визначення калорій

calories_map = {"meat": 100, "rice": 20, "egg": 10}
meals_map = {"meat": 150, "rice": 200, "egg": 1}

calories = np.array(list(calories_map.values()))
meals = np.array(list(meals_map.values()))

# (продукти,) @ (продукти,) -> ()
total = calories @ meals
total

19010

In [ ]:
# багато страв, 1 метод визначення калорій
calories_map = {"meat": 100, "rice": 20, "egg": 10}

meals_map1 = {"meat": 150, "rice": 200, "egg": 1}
meals_map2 = {"meat": 50, "rice": 150, "egg": 2}
meals_map3 = {"meat": 200, "rice": 100, "egg": 3}

calories = np.array(list(calories_map.values()))

meals1 = np.array(list(meals_map1.values()))
meals2 = np.array(list(meals_map2.values()))
meals3 = np.array(list(meals_map3.values()))

all_meals = np.array([meals1, meals2, meals3])

# (n, m) @ (m, k)
# (страва, продукт) @ (продукт) -> (страва,)
# (продукт) @ (страва, продукт) -> error

all_meals @ calories

array([19010,  8020, 22030])

In [ ]:
# багато страв, багато метод визначення калорій
calories_map1 = {"meat": 100, "rice": 20, "egg": 10}
calories_map2 = {"meat": 101, "rice": 21, "egg": 11}
calories_map3 = {"meat": 99, "rice": 19, "egg": 12}

meals_map1 = {"meat": 150, "rice": 200, "egg": 1}
meals_map2 = {"meat": 50, "rice": 150, "egg": 2}
meals_map3 = {"meat": 200, "rice": 100, "egg": 3}

calories1 = np.array(list(calories_map1.values()))
calories2 = np.array(list(calories_map2.values()))
calories3 = np.array(list(calories_map3.values()))

meals1 = np.array(list(meals_map1.values()))
meals2 = np.array(list(meals_map2.values()))
meals3 = np.array(list(meals_map3.values()))

all_calories = np.array([calories1, calories2, calories3])
all_meals = np.array([meals1, meals2, meals3])

# (страва, продукт) @ (метод, продукт) -> error
# (метод, продукт) @ (страва, продукт) -> error
# транспонування
# (страва, продукт) @ (продукт, метод) -> (страва, метод)

all_meals @ all_calories.T

array([[19010, 19361, 18662],
       [ 8020,  8222,  7824],
       [22030, 22333, 21736]])

Окрім функцій, які перевантажують оператори, Numpy також надає багато корисних функцій для виконання обчислень у масивах, таких як `min()`, `max()`, `sum()` та інші:

![](http://jalammar.github.io/images/numpy/numpy-matrix-aggregation-1.png)

In [ ]:
x = np.array([[1, 2], [3, 4], [5, 6]])

print(np.max(x))  # Compute max of all elements; prints "6"
print(np.min(x))  # Compute min of all elements; prints "1"
print(np.sum(x))  # Compute sum of all elements; prints "21"

Ми можемо застосовувати ці функції не тільки по всіх значеннях в матриці, але застосовувати їх по рядках або стовпцях за допомогою параметра `axis`:

![](http://jalammar.github.io/images/numpy/numpy-matrix-aggregation-4.png)

In [ ]:
x = np.array([[1, 2], [5, 3], [4, 6]])

print(np.max(x, axis=0))  # Compute max of each column; prints "[5 6]"
print(np.max(x, axis=1))  # Compute max of each row; prints "[2 5 6]"

Ви можете знайти повний список математичних функцій, які надає numpy, у [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Окрім обчислення математичних функцій за допомогою масивів, нам часто потрібно змінювати форму або іншим чином маніпулювати даними в масивах. Найпростішим прикладом цього типу операції є транспонування матриці; щоб транспонувати матрицю, просто використовуйте атрибут T об’єкта масиву.

![](http://jalammar.github.io/images/numpy/numpy-transpose.png)

In [ ]:
x = np.array([[1, 2], [3, 4], [5, 6]])

print(x)
print("transpose\n", x.T)

[[1 2]
 [3 4]
 [5 6]]
transpose
 [[1 3 5]
 [2 4 6]]


In [ ]:
v = np.array([[1,2,3]])
print(v )
print("transpose\n", v.T)

[[1 2 3]]
transpose
 [[1]
 [2]
 [3]]


У більш просунутому випадку використання вам може знадобитися змінити розміри певної матриці. Це часто буває в програмах машинного навчання, де певна модель очікує певної форми для вхідних даних, яка відрізняється від вашого набору даних. Метод numpy `reshape()` корисний у цих випадках.

![](http://jalammar.github.io/images/numpy/numpy-reshape.png)

In [ ]:
w = np.arange(6)
print(w)
w.shape

[0 1 2 3 4 5]


(6,)

In [ ]:
u = w.reshape((2, 3))
print(u)
u.shape

[[0 1 2]
 [3 4 5]]


(2, 3)

Ми можемо передати -1 як один вимір, і numpy визначить правильний розмір на основі розміру нашої матриці

In [ ]:
y = w.reshape((-1, 2))
print(y)
y.shape

Часто в масивах є розмірності розміром в 1, що потрібно для алгоритмів, але не несе жодної додаткової інформації.

Функція `squeeze()`, яка видаляє *всі* «непотрібні» розміри (розміри, які мають розмір 1) з масиву:

In [ ]:
x = np.ones((1, 5))
y = x.squeeze()
print(x, x.shape)
print(y, y.shape)

[[1. 1. 1. 1. 1.]] (1, 5)
[1. 1. 1. 1. 1.] (5,)


### Трансляція

Трансляція - це потужний механізм, який дозволяє numpy працювати з масивами різної форми під час виконання арифметичних операцій.

Наприклад: в лінійній алгебрі ми можемо лише додаватити (і виконати інші поелементні операції) дві матриці, які мають *однаковий* розмір. У numpy, якщо ми хочемо додати дві матриці з різними розмірами, numpy неявно «розширить» розмірність однієї матриці, щоб відповідати іншій, щоб ми могли виконати операцію.

Таким чином, ці операції працюватимуть, а не повертатимуть помилку:

![](https://sebastianraschka.com/images/blog/2020/numpy-intro/broadcasting-1.png)

![](https://sebastianraschka.com/images/blog/2020/numpy-intro/broadcasting-2.png)

Трансляція двох масивів відповідає таким правилам:

**Правило 1**: якщо два масиви відрізняються за кількістю вимірів, форма масиву з меншою кількістю вимірів доповнюється одиницями на його першій (лівій) стороні.

Наприклад, у наступній клітинці "a" буде неявно розширено до форми (1,3):

In [ ]:
a = np.array([1,2,3])         # has shape (3,): one dimension
b = np.array([[4], [5], [6]]) # has shape (3,1): two dimensions
c = a + b                     # will have shape (3,3) (two dimensions)

**Правило 2**: якщо форма двох масивів не збігається в жодному вимірі, масив, форма якого дорівнює 1 у цьому вимірі, розтягується, щоб відповідати іншій формі.

Наприклад, у наступній клітинці `a` буде неявно розширено до форми (3,2):

In [ ]:
a = np.array([[1],[2],[3]])         # has shape (3,1)
b = np.array([[4,5], [6,7], [8,9]]) # has shape (3,2)
c = a + b                           # will have shape (3,2)

**Правило 3**: якщо в будь-якому вимірі розміри не збігаються і жоден не дорівнює 1, виникає помилка:

In [ ]:
a = np.array([[1],[2],[3],[4]])      # has shape (4,1)
b = np.array([[4,5], [6,7], [8,9]])  # has shape (3,2)
c = a + b                            # ValueError: operands could not be broadcast

Більше інформації [documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html).

Функції, які підтримують трансляцію, відомі як універсальні функції. Ви можете знайти список усіх універсальних функцій у [documentation](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).


Ось кілька наочних прикладів, що стосуються трансляції.

![](http://jalammar.github.io/images/numpy/numpy-array-broadcast.png)

Зауважте, що ці масиви сумісні в кожному вимірі, якщо вони мають однаковий розмір у цьому вимірі або якщо один масив має розмір 1 у цьому вимірі.

![](http://jalammar.github.io/images/numpy/numpy-matrix-broadcast.png)

And here are some more practical applications:

In [ ]:
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)

In [ ]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

print(x + v)

[[2 4 6]
 [5 7 9]]


In [ ]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:

print((x.T + w).T)

In [ ]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

In [ ]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print(x * 2)

Трансляція зазвичай робить ваш код більш лаконічним і швидшим, тому ви повинні прагнути використовувати його, де це можливо.

Цей короткий огляд торкнувся багатьох важливих речей, які вам потрібно знати про numpy, але він далеко не повний. Перегляньте [numpy](http://docs.scipy.org/doc/numpy/reference/), щоб дізнатися більше про numpy.